### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by cmceezee** [chiedolabs/stl_parser#2]
Hi,
I've been able to point a STL file path to the parser and ruby gives me the following error: 

No such file or directory @ rb_sysopen - /uploads/project/project_file/49/dino.stl

Any thoughts?  Many thanks!

Chris

**Comment by chiedo** [comment]
It sounds like you're just not pointing to the right place!

Do some googling about rails_root

**Comment by cmceezee** [comment]
Thanks for the quick response.  So yea, I tried the root_url, concatenated a string which was the full file URL, which if I copy / paste the file URL into my browser, opens up the STL.  The parser basically needs to know where the STL File lives right?

I use thingiview.js to render the 3D model in a viewer using the same URL string.  I’ve tried all variations of the root and partial URLs.  Could it be something else?  

Thanks!

**Comment by chiedo** [comment]
Yeah it needs to know where the STL file lives.

Sorry, I'm not sure what the issue is in that case :( The code that reads
the file is pretty simple though so feel free to read the source code!


*--*

*Chiedo* [chay-dough]

*CHIE**DO **LABS:* Fast Communication. Rock-solid Apps. Amazing Websites.

*FounderBy*30*:* Transforming Entrepreneurs Under 30 Into Extraordinary
Founders.

James Madison University 2013

Aletheia Church

**Comment by cmceezee** [comment]
Okay well if you have any thoughts from this screenshot, I'm all ears:
<img width="1420" alt="screen shot 2017-12-25 at 1 17 22 pm" src="https://user-images.githubusercontent.com/4522129/34342976-6ebaed68-e976-11e7-90cf-f8658a7b34e0.png">

**Comment by chiedo** [comment]
Sorry @cmceezee, not sure!  If you figure out it's an issue with the library though as opposed to an issue on your end, please let me know the fix!

**Comment by cmceezee** [comment]
Thanks @chiedo !  With enough hours and head pounding, I'll eventually figure it out.  Here's my stackoverflow post in case you're curious:  https://stackoverflow.com/questions/47999507/errnoenoent-no-file-exists-but-file-does-exist-works-locally-not-in-aws

**Comment by cmceezee** [comment]
It looks like there is an issue with using file.open() for passing URLs.   See this StackOverflow: https://stackoverflow.com/questions/263536/open-an-io-stream-from-a-local-file-or-url

I don't know how to fix my problem without tweaking your gem itself.  Thoughts?   Thanks!

**Comment by chiedo** [comment]
@hertling thoughts? Re: your contribution.

https://github.com/chiedolabs/stl_parser/commit/25e352a5fb0c690801803bde3124b6914f9841d8

**Comment by cmceezee** [comment]
Gentlemen...figured it out.  Two key steps:

1) Copy / pasted @chiedo 's STL_parser code into its own ruby file (STL_parser.rb) into our application>lib folder with the following code:
`require 'open-uri'` as line number 1 of that file.

2) Updated our config>application.rb file to include:
`require_relative '../lib/stl_parser'`  

to utilize the modified STL_parser.rb file which now utilizes 'open-uri' library--which is apparently native to ruby.  More details can be found here: https://stackoverflow.com/questions/263536/open-an-io-stream-from-a-local-file-or-url

This enabled us to pass a URL of an STL file to @chiedo 's STL_parser algorithm from AWS...which I assume how most cloud services serve non HTML-related files.  

Hope that makes sense.   Happy coding!

**Comment by chiedo** [comment]
You rock @cmceezee thanks!
